# Generated by Django 6.0.2 on 2026-02-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleListing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='year',
            field=models.IntegerField(),
        ),
    ]
