# Generated by Django 6.0.2 on 2026-02-13 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VehicleListing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('start_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pick_up', models.CharField(max_length=50)),
                ('drop_off', models.CharField(max_length=50)),
                ('days', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='VehicleListing.vehicles')),
            ],
        ),
    ]
